# Generated by Django 3.1.14 on 2024-06-03 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.TextField(default='')),
                ('telefone', models.CharField(default='', max_length=20)),
                ('credito', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paga', models.BooleanField()),
                ('pessoa', models.ForeignKey(default='Admin', on_delete=django.db.models.deletion.CASCADE, to='noronhanotas.pessoa')),
            ],
        ),
    ]
