# Generated by Django 3.1.14 on 2024-09-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noronhanotas', '0002_auto_20240602_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=11),
            preserve_default=False,
        ),
    ]
