# Generated by Django 3.1.14 on 2024-09-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noronhanotas', '0003_pessoa_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=11),
        ),
    ]
