# Generated by Django 3.1.14 on 2024-09-25 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noronhanotas', '0004_auto_20240924_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='noronhanotas.pessoa'),
        ),
    ]
