# Generated by Django 3.1.14 on 2024-09-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noronhanotas', '0006_auto_20240925_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='data_venc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
