# Generated by Django 3.1.14 on 2024-09-26 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noronhanotas', '0007_auto_20240925_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='data_venc',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='vencimento',
        ),
        migrations.AddField(
            model_name='notas',
            name='dataRecebimento',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='notas',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
