# Generated by Django 3.1.14 on 2024-09-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noronhanotas', '0008_auto_20240926_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='paga',
        ),
    ]
