# Generated by Django 3.1.14 on 2024-10-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noronhanotas', '0009_remove_notas_paga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='comprovante',
        ),
        migrations.AddField(
            model_name='notas',
            name='atrasada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='somanotas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
