# Generated by Django 3.1.14 on 2024-11-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noronhanotas', '0011_auto_20241002_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='valoratrasado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='valorpendente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
